name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./word_counter
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: "Python Poetry Action"
        uses: abatilo/actions-poetry@v2.1.0
      - name: Run linters
        run: make lint
      - name: Run tests
        run: make test
